[project]
name = "scaffold_branch_demo"
requires-python = ">=3.9,<3.14"
version = "0.1.0"
dependencies = [
    "dagster",
    "dagster-pipes",
    "dagster-shared",
    "dagster-test",
]

[dependency-groups]
dev = [
    "dagster-webserver",
    "dagster-graphql",
    "dagster-dg-core",
    "dagster-dg-cli",
    "dagster-cloud-cli",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "scaffold_branch_demo"
registry_modules = [
    "scaffold_branch_demo.components.*",
]

[tool.uv.sources]
dagster-test = { path = '/Users/ben/repos/dagster/python_modules/dagster-test', editable = true }
dagster-graphql = { path = '/Users/ben/repos/dagster/python_modules/dagster-graphql', editable = true }
dagster = { path = '/Users/ben/repos/dagster/python_modules/dagster', editable = true }
dagster-pipes = { path = '/Users/ben/repos/dagster/python_modules/dagster-pipes', editable = true }
dagster-webserver = { path = '/Users/ben/repos/dagster/python_modules/dagster-webserver', editable = true }
dagster-airbyte = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-airbyte', editable = true }
dagster-dask = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-dask', editable = true }
dagster-github = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-github', editable = true }
dagster-snowflake = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-snowflake', editable = true }
dagster-pagerduty = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-pagerduty', editable = true }
dagster-cloud-cli = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-cloud-cli', editable = true }
dagster-prometheus = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-prometheus', editable = true }
dagster-deltalake = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-deltalake', editable = true }
dagster-dlt = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-dlt', editable = true }
dagster-azure = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-azure', editable = true }
dagster-postgres = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-postgres', editable = true }
dagster-duckdb = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-duckdb', editable = true }
dagster-gcp-pandas = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-gcp-pandas', editable = true }
dagster-k8s = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-k8s', editable = true }
dagster-papertrail = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-papertrail', editable = true }
dagster-gcp-pyspark = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-gcp-pyspark', editable = true }
dagster-celery = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-celery', editable = true }
dagster-airflow = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-airflow', editable = true }
dagster-dbt = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-dbt', editable = true }
dagster-census = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-census', editable = true }
dagster-airlift = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-airlift', editable = true }
dagster-managed-elements = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-managed-elements', editable = true }
dagster-snowflake-pandas = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-snowflake-pandas', editable = true }
dagster-embedded-elt = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-embedded-elt', editable = true }
dagster-powerbi = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-powerbi', editable = true }
dagster-pandera = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-pandera', editable = true }
dagster-datadog = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-datadog', editable = true }
dagster-celery-k8s = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-celery-k8s', editable = true }
dagster-pandas = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-pandas', editable = true }
dagster-openai = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-openai', editable = true }
dagster-snowflake-polars = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-snowflake-polars', editable = true }
dagster-twilio = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-twilio', editable = true }
dagster-gcp = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-gcp', editable = true }
dagstermill = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagstermill', editable = true }
dagster-duckdb-pandas = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-duckdb-pandas', editable = true }
dagster-ge = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-ge', editable = true }
dagster-sigma = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-sigma', editable = true }
dagster-pyspark = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-pyspark', editable = true }
dagster-ssh = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-ssh', editable = true }
dagster-deltalake-polars = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-deltalake-polars', editable = true }
dagster-mysql = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-mysql', editable = true }
dagster-docker = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-docker', editable = true }
dagster-duckdb-pyspark = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-duckdb-pyspark', editable = true }
dagster-looker = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-looker', editable = true }
dagster-duckdb-polars = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-duckdb-polars', editable = true }
dagster-msteams = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-msteams', editable = true }
dagster-datahub = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-datahub', editable = true }
dagster-databricks = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-databricks', editable = true }
dagster-deltalake-pandas = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-deltalake-pandas', editable = true }
dagster-fivetran = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-fivetran', editable = true }
dagster-sling = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-sling', editable = true }
dagster-dg-cli = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-dg-cli', editable = true }
dagster-slack = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-slack', editable = true }
dagster-aws = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-aws', editable = true }
dagster-dg-core = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-dg-core', editable = true }
dagster-mlflow = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-mlflow', editable = true }
dagster-tableau = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-tableau', editable = true }
dagster-shared = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-shared', editable = true }
dagster-snowflake-pyspark = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-snowflake-pyspark', editable = true }
dagster-celery-docker = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-celery-docker', editable = true }
dagster-spark = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-spark', editable = true }
dagster-wandb = { path = '/Users/ben/repos/dagster/python_modules/libraries/dagster-wandb', editable = true }
create-dagster = { path = '/Users/ben/repos/dagster/python_modules/libraries/create-dagster', editable = true }
